language: node_js
node_js:
  - "4"

# Environment Variables
env:
  # Global Variables
  global:
    - GH_REF=github.com/dust8/dust8.github.io

before_install:
  - git config user.name "dust8"
  - git config user.email "adbcdust@gmail.com"

install:
  - npm install hexo-cli -g
  - npm install hexo-generator-feed --save
  - npm install hexo-generator-index --save
  - npm install hexo-generator-archive --save
  - npm install hexo-generator-tag --save
  - npm install

script:
  - hexo clean
  - hexo generate --debug

after_script:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master

# Building Specific Branches
branches:
  only:
    - blog-source

cache:
  directories:
    - node_modules
